apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: replication 
  name: failover-placement-0
  namespace: dokuwiki
spec:
  clusterSelector:
    matchExpressions: []
    matchLabels:
      site: failover
