apiVersion: snapshot.storage.k8s.io/v1beta1
deletionPolicy: Delete
driver: hostpath.csi.k8s.io
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: csi-hostpath-snapclass
