apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: replication 
  annotations:
    apps.open-cluster-management.io/github-path: rclone-acm-dokuwiki/source-rclone
    apps.open-cluster-management.io/github-branch: main 
  name: replication-source
  namespace: dokuwiki
spec:
  channel: dokuwiki/file
  placement:
    placementRef:
      kind: PlacementRule
      name: datasource-placement-0
