apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rclone-acm-dokuwiki/remote-application
  labels:
    app: dokuwiki
  name: dokuwiki-subscription-0
  namespace: dokuwiki
spec:
  channel: dokuwiki/file
  placement:
    placementRef:
      kind: PlacementRule
      name: remote-placement-0
