apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rclone-acm-dokuwiki/application/remote-application/overlays/hostpath
  labels:
    app: dokuwiki
  name: dokuwiki-hostpath-subscription-0
  namespace: dokuwiki
spec:
  channel: dokuwiki/file
  placement:
    placementRef:
      kind: PlacementRule
      name: hostpath-placement-0
