apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: acm-pricelist-demo/application-code
  labels:
    app: pricelist
  name: pricelist-subscription-0
  namespace: pricelist
spec:
  channel: pricelist/file
  placement:
    placementRef:
      kind: PlacementRule
      name: pricelist-placement-0
