---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: database-destination
  namespace: dokuwiki 
spec:
  trigger:
    schedule: "*/5 * * * *"
  rclone:
    volumeSnapshotClassName: gp2-csi
