apiVersion: batch/v1
kind: Job
metadata:
  name: chown-pvc 
  namespace: dokuwiki 
spec:
  template:
    spec:
      containers:
      - name: change-ownership 
        image: registry.redhat.io/openshift4/ose-cli:latest
        securityContext:
          runAsUser: 0
        command: ["/bin/bash","-c","chown 1002230000:1002230000 -R /bitnami/dokuwiki"]
        volumeMounts:
        - mountPath: /bitnami/dokuwiki
          name: dokuwiki-data
      serviceAccount: chown
      privileged: true
      volumes:
      - name: dokuwiki-data
        persistentVolumeClaim:
          claimName: dokuwiki
      restartPolicy: Never
  backoffLimit: 4
