apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-client
  name: mysql-client
  namespace: database
spec:
  containers:
  - args:
    - /bin/bash
    - -c
    - sleep 4000
    image: mysql
    envFrom:
    - secretRef:
        name: aws-rdspostgresql-conn
    name: mysql-client
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
