apiVersion: packages.crossplane.io/v1alpha1
kind: ClusterPackageInstall
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"packages.crossplane.io/v1alpha1","kind":"ClusterPackageInstall","metadata":{"annotations":{},"name":"provider-aws","namespace":"openshift-operators"},"spec":{"package":"crossplane/provider-aws:v0.11.1"}}
  name: provider-aws
  namespace: database 
spec:
  package: crossplane/provider-aws:v0.11.1
