apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: database-internetgateway
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: database-vpc
  providerConfigRef:
    name: aws-provider
--- 
apiVersion: ec2.aws.crossplane.io/v1alpha4
kind: RouteTable
metadata:
  name: database-routetable
spec:
  forProvider:
    region: us-east-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: database-internetgateway
    associations:
      - subnetIdRef:
          name: subnet1 
      - subnetIdRef:
          name: subnet2
    vpcIdRef:
      name: database-vpc
  providerConfigRef:
    name: aws-provider
