apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: db-subnet-group
spec:
  forProvider:
    region: us-east-1
    description: "Database Subnet group"
    subnetIdRefs:
      - name: subnet1 
      - name: subnet2
  providerConfigRef:
    name: aws-provider
