apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: database-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags:
    - key: Name
      value: database-vpc
  providerRef:
    name: aws-provider 
