apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dokuwiki
    namespace: dokuwiki
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: gp2
    volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
