---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: dokuwiki 
spec:
  sourcePVC: mysql-pv-claim
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: a0c89b84ce44c4421a62dfaf2e56d7cb-953a0a17ee0e32a2.elb.us-east-2.amazonaws.com
    copyMethod: Snapshot
    volumeSnapshotClassName: ocs-storagecluster-rbdplugin-snapclass
