---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: dokuwiki 
spec:
  sourcePVC: dokuwiki
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: af53d92d2173341d1a24779519a0fbe3-0ca9bd45a000bcea.elb.us-east-1.amazonaws.com
    copyMethod: Snapshot
    volumeSnapshotClassName: ocs-storagecluster-rbdplugin-snapclass
