---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: database 
spec:
  sourcePVC: mysql-pv-claim
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: a082491ff7f924cffa0ee20c0d8f6c7f-ddba845429fd21bc.elb.us-west-1.amazonaws.com 
    copyMethod: Snapshot
    volumeSnapshotClassName: gp2-csi 
