---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: dokuwiki 
spec:
  sourcePVC: dokuwiki
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: a48a38bf6f69c4070831391e8b22e8d5-08027986c9de8c10.elb.us-east-2.amazonaws.com 
    copyMethod: Snapshot
    volumeSnapshotClassName: gp2-csi 
