---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: database-destination
  namespace: dokuwiki 
spec:
  trigger:
    schedule: "*/5 * * * *"
  rclone:
    rcloneConfigSection: "aws-s3-bucket"
    rcloneDestPath: "rcook-backup"
    rcloneConfig: "rclone-secret"
    copyMethod: None 
    accessModes: [ReadWriteOnce]
    capacity: 8Gi
