---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: pricelist 
spec:
  sourcePVC: mysql-pv-claim
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: a868952c2c7294e43a696fb257c40737-becff566a2a915a9.elb.us-east-2.amazonaws.com
    copyMethod: Snapshot
    volumeSnapshotClassName: ocs-storagecluster-rbdplugin-snapclass
