---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: pricelist 
spec:
  sourcePVC: mysql-pv-claim
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: acf23ec7a9ba34da98ebdd654c0941c3-d2ff990cc66603b0.elb.us-east-2.amazonaws.com
    copyMethod: Snapshot
    volumeSnapshotClassName: ocs-storagecluster-rbdplugin-snapclass
