---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uploader-pvc 
  namespace: uploader 
spec:
  rsync:
    serviceType: LoadBalancer
    copyMethod: None 
    destinationPVC: uploader-pvc
    sshKeys: scribe-key
