apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: replication 
  name: primary-placement-0
  namespace: pricelist
spec:
  clusterSelector:
    matchExpressions: []
    matchLabels:
      site: primary
