apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: storageclass
  name: ocs-placement-0
  namespace: default
spec:
  clusterSelector:
    matchExpressions: []
    matchLabels:
      storage: ocs
