apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: storageclass
  annotations:
    apps.open-cluster-management.io/github-path: storage-class-modifications/osp
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/reconcile-option: merge
  name: aws-storageclass
  namespace: default
spec:
  channel: default/file
  placement:
    placementRef:
      kind: PlacementRule
      name: aws-placement-0
