apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: uploader
  name: uploader-placement-0
  namespace: uploader
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      purpose: uploader
