apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: replication 
  name: gp2-app-remote-placement-0
  namespace: dokuwiki
spec:
  clusterSelector:
    matchExpressions: []
    matchLabels:
      storage: gp2
