apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: replication 
  annotations:
    apps.open-cluster-management.io/github-path: rclone-acm-dokuwiki/destination-rclone
    apps.open-cluster-management.io/github-branch: main 
  name: app-replication-remote
  namespace: dokuwiki
spec:
  channel: dokuwiki/file
  placement:
    placementRef:
      kind: PlacementRule
      name: app-remote-placement-0
