apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  labels:
    app: scribe
  name: scribe-subscription
  namespace: scribe-system
spec:
  channel: scribe-system/scribe 
  name: scribe
  packageOverrides:
  - packageName: scribe
    packageAlias: scribe
  placement:
    placementRef:
      kind: PlacementRule
      name: scribe-placement-0
