---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: dokuwiki 
spec:
  sourcePVC: dokuwiki
  trigger:
    schedule: "*/59 * * * *"
  rclone:
    rcloneConfigSection: "aws-s3-bucket"
    rcloneDestPath: "rcook-backup"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
