---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: dokuwiki 
spec:
  sourcePVC: dokuwiki
  trigger:
    schedule: "*/2 * * * *"
  rclone:
    rcloneConfigSection: "aws-s3-bucket"
    direction: "source"
    mountPath: "/data"
    rcloneDestPath: "east2-backup-rcook"
    rcloneConfig: "/rclone-config/rclone.conf"
    copyMethod: Snapshot
