---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uploader-destination
  namespace: uploader 
spec:
  rsync:
    serviceType: LoadBalancer
    copyMethod: None
    destinationPVC: uploader
    capacity: 2Gi
    accessModes: [ReadWriteOnce]
