---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: database-destination
  namespace: database 
spec:
  rsync:
    serviceType: LoadBalancer
    copyMethod: Snapshot 
    capacity: 2Gi
    accessModes: [ReadWriteOnce]
