---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uploader-destination
  namespace: uploader 
spec:
  rsync:
    serviceType: ClusterIP
    copyMethod: Snapshot
    capacity: 2Gi
    accessModes: [ReadWriteOnce]
