---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: upload-source
  namespace: database 
spec:
  sourcePVC: upload
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: aaa5c3958bbfe48fe964d4bc2829235c-de78ec92d2ae2077.elb.us-west-2.amazonaws.com
    copyMethod: Snapshot
