---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki
  namespace: dokuwiki
spec:
  accessModes:
    - ReadWriteOnce
#  dataSource:
#    kind: VolumeSnapshot
#    apiGroup: snapshot.storage.k8s.io
#    name: volsync-dest-database-destination-20211004043439
  resources:
    requests:
      storage: 2Gi
