apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki
  namespace: dokuwiki
spec:
  storageClassName: gp2-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
