apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki
  namespace: dokuwiki
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
