apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dokuwiki 
  name: snapshot-changer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update"]
